v9.1.0

diff --git a/opt/cardano/cnode/scripts/env b/opt/cardano/cnode/scripts/env
--- a/opt/cardano/cnode/scripts/env
+++ b/opt/cardano/cnode/scripts/env
@@ -11,7 +11,7 @@
 #CCLI="${HOME}/.local/bin/cardano-cli"                  # Override automatic detection of cardano-cli executable
 #CNCLI="${HOME}/.local/bin/cncli"                       # Override automatic detection of executable (https://github.com/AndrewWestberg/cncli)
 #CNODE_HOME="/opt/cardano/cnode"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
-CNODE_PORT=6000                                        # Set node port
+#CNODE_PORT=6000                                        # Set node port
 #CONFIG="${CNODE_HOME}/files/config.json"               # Override automatic detection of node config path
 #SOCKET="${CNODE_HOME}/sockets/node.socket"            # Override automatic detection of path to socket
 #TOPOLOGY="${CNODE_HOME}/files/topology.json"           # Override default topology.json path
@@ -49,14 +49,42 @@ CNODE_PORT=6000                                        # Set node port
 #WALLET_PAY_SK_FILENAME="payment.skey"
 #WALLET_HW_PAY_SK_FILENAME="payment.hwsfile"
 #WALLET_PAY_ADDR_FILENAME="payment.addr"
+#WALLET_PAY_SCRIPT_FILENAME="payment.script"
+#WALLET_PAY_CRED_FILENAME="payment.cred"
+#WALLET_PAY_SCRIPT_CRED_FILENAME="payment.script.cred"
 #WALLET_BASE_ADDR_FILENAME="base.addr"
 #WALLET_STAKE_VK_FILENAME="stake.vkey"
 #WALLET_STAKE_SK_FILENAME="stake.skey"
 #WALLET_HW_STAKE_SK_FILENAME="stake.hwsfile"
 #WALLET_STAKE_ADDR_FILENAME="reward.addr"
+#WALLET_STAKE_SCRIPT_FILENAME="stake.script"
+#WALLET_STAKE_CRED_FILENAME="stake.cred"
+#WALLET_STAKE_SCRIPT_CRED_FILENAME="stake.script.cred"
 #WALLET_STAKE_CERT_FILENAME="stake.cert"
 #WALLET_STAKE_DEREG_FILENAME="stake.dereg"
 #WALLET_DELEGCERT_FILENAME="delegation.cert"
+#WALLET_VOTE_CATALYST_VK_FILENAME="catalyst.vkey"
+#WALLET_VOTE_CATALYST_SK_FILENAME="catalyst.skey"
+#WALLET_VOTE_CATALYST_QR_FILENAME="catalyst-qrcode.png"
+#WALLET_GOV_DREP_VK_FILENAME="drep.vkey"
+#WALLET_GOV_DREP_SK_FILENAME="drep.skey"
+#WALLET_GOV_DREP_ID_FILENAME="drep.id"
+#WALLET_GOV_DREP_SCRIPT_FILENAME="drep.script"
+#WALLET_GOV_DREP_REGISTER_CERT_FILENAME="drep-reg.cert"
+#WALLET_GOV_DREP_RETIRE_CERT_FILENAME="drep-ret.cert"
+#WALLET_GOV_VOTE_DELEG_CERT_FILENAME="vote-deleg.cert"
+#WALLET_GOV_HW_DREP_SK_FILENAME="drep.hwsfile"
+#WALLET_GOV_CC_HOT_VK_FILENAME="cc-hot.vkey"
+#WALLET_GOV_CC_HOT_SK_FILENAME="cc-hot.skey"
+#WALLET_GOV_HW_CC_HOT_SK_FILENAME="cc-hot.hwsfile"
+#WALLET_GOV_CC_HOT_ID_FILENAME="cc-hot.id"
+#WALLET_GOV_CC_COLD_VK_FILENAME="cc-cold.vkey"
+#WALLET_GOV_CC_COLD_SK_FILENAME="cc-cold.skey"
+#WALLET_GOV_HW_CC_COLD_SK_FILENAME="cc-cold.hwsfile"
+#WALLET_GOV_CC_COLD_ID_FILENAME="cc-cold.id"
+#WALLET_DERIVATION_PATH_FILENAME="derivation.path"
+
+#WALLET_MULTISIG_PREFIX="ms_"                           # Filename for multisig files, uses separate keys derived using the 1854H paths
 
 #POOL_ID_FILENAME="pool.id"                             # Standardized names for all pool related files
 #POOL_HOTKEY_VK_FILENAME="hot.vkey"
@@ -82,6 +110,7 @@ CNODE_PORT=6000                                        # Set node port
 #CIP0094_POLL_URL="https://raw.githubusercontent.com/cardano-foundation/CIP-0094-polls/main/networks/polls.json" # URL for polls to vote against
 
 #MITHRIL_DOWNLOAD="N"                                   # (Y|N) Download latest Mithril snapshot
+#MITHRIL_SIGNER_ENABLED="N"                             # (Y|N) Enable the gLiveView Mithril Signer Section
 
 #STRICT_VERSION_CHECK="Y"                               # (Y|N) Restrict operation to supported major.minor version leaving patch version open. If disabled, any version will be accepted (unsupported)
 
@@ -107,6 +136,13 @@ is_dir() {
 #             : $1=minimal_needed_version
 #             : $2=current_version
 versionCheck() {
+  printf '%s\n%s' "${1//v/}" "${2//v/}" | sort -C -V;
+}
+
+# Description : Specific node/cli version check that take STRICT_VERSION_CHECK into account and only look at Major.Minor
+#             : $1=minimal_needed_version
+#             : $2=current_version
+versionCheckNode() {
   [[ ${STRICT_VERSION_CHECK} = N ]] && return 0
   w_ver=${1//v/}; w_ver_dots=${w_ver//[^.]}; [[ ${#w_ver_dots} -gt 1 && ${w_ver} =~ ^([0-9]+.[0-9]) ]] && w_ver=${BASH_REMATCH[1]}
   c_ver=${2//v/}; c_ver_dots=${c_ver//[^.]}; [[ ${#c_ver_dots} -gt 1 && ${c_ver} =~ ^([0-9]+.[0-9]) ]] && c_ver=${BASH_REMATCH[1]}
@@ -167,7 +203,6 @@ checkUpdate() {
     fi
   fi
   [[ -n $5 ]] && URL="${URL_RAW}/scripts/$5" || URL="${URL_RAW}/scripts/cnode-helper-scripts"
-  URL_DOCS="${URL_RAW}/docs/Scripts"
   if curl -s -f -m ${CURL_TIMEOUT} -o "${dname}/${fname}".tmp "${URL}/${fname}" 2>/dev/null; then
 
     # make sure script exist, else just rename
@@ -249,8 +284,11 @@ checkUserVariables() {
 #             : $1 = executable to validate
 cmdAvailable() {
   if ! command -v "$1" &>/dev/null; then
-    printf "${FG_RED}ERROR${NC}: need '$1' (command not found)\nplease install with your packet manager of choice(apt/yum etc..) and relaunch CNTools\nhttps://command-not-found.com/$1" 1>&2
+    printf "${FG_RED}ERROR${NC}: need '$1' (command not found)\nplease install with your packet manager of choice(apt/dnf etc..) and relaunch CNTools\nhttps://command-not-found.com/$1" 1>&2
     return 1
+  elif [[ ! -x $(command -v "$1") ]]; then
+    printf "${FG_RED}ERROR${NC}: '$1' missing executable permission, please fix" 1>&2
+    return 2
   fi
   return 0
 }
@@ -545,7 +583,9 @@ getNodeMetrics() {
     .cardano.node.metrics.connectionManager.outgoingConns.val //0,
     .cardano.node.metrics.connectionManager.unidirectionalConns.val //0,
     .cardano.node.metrics.connectionManager.duplexConns.val //0,
-    .cardano.node.metrics.connectionManager.prunableConns.val //0
+    .cardano.node.metrics.connectionManager.prunableConns.val //0,
+    .cardano.node.metrics.forging_enabled.val //0,
+    .cardano.node.metrics.cardano_build_info.val //"-"
     ] | @tsv' <<< "${node_metrics}")
     read -ra node_metrics_arr <<< ${node_metrics_tsv}
     blocknum=${node_metrics_arr[0]}; epochnum=${node_metrics_arr[1]}; slot_in_epoch=${node_metrics_arr[2]}; slotnum=${node_metrics_arr[3]}
@@ -564,6 +604,9 @@ getNodeMetrics() {
     peers_cold=${node_metrics_arr[26]}; peers_warm=${node_metrics_arr[27]}; peers_hot=${node_metrics_arr[28]}
     conn_incoming=${node_metrics_arr[29]}; conn_outgoing=${node_metrics_arr[30]}
     conn_uni_dir=${node_metrics_arr[31]}; conn_bi_dir=${node_metrics_arr[32]}; conn_duplex=${node_metrics_arr[33]}
+    forging_enabled=${node_metrics_arr[34]}
+    [[ ${node_metrics_arr[35]} =~ ,version=\"([0-9.]*)\" ]] && running_node_version=${BASH_REMATCH[1]} || running_node_version="?"
+    [[ ${node_metrics_arr[35]} =~ ,revision=\"([0-9a-f]*)\" ]] && running_node_rev=${BASH_REMATCH[1]:0:8} || running_node_rev="?"
   else
     node_metrics=$(curl -s -m ${EKG_TIMEOUT} "http://${PROM_HOST}:${PROM_PORT}/metrics" 2>/dev/null)
     [[ ${node_metrics} =~ cardano_node_metrics_blockNum_int[[:space:]]([^[:space:]]*) ]] && blocknum=${BASH_REMATCH[1]} || blocknum=0
@@ -600,6 +643,9 @@ getNodeMetrics() {
     [[ ${node_metrics} =~ cardano_node_metrics_connectionManager_unidirectionalConns[[:space:]]([^[:space:]]*) ]] && conn_uni_dir=${BASH_REMATCH[1]} || conn_uni_dir=0
     [[ ${node_metrics} =~ cardano_node_metrics_connectionManager_duplexConns[[:space:]]([^[:space:]]*) ]] && conn_bi_dir=${BASH_REMATCH[1]} || conn_bi_dir=0
     [[ ${node_metrics} =~ cardano_node_metrics_connectionManager_prunableConns[[:space:]]([^[:space:]]*) ]] && conn_duplex=${BASH_REMATCH[1]} || conn_duplex=0
+    [[ ${node_metrics} =~ cardano_node_metrics_forging_enabled[[:space:]]([^[:space:]]*) ]] && forging_enabled=${BASH_REMATCH[1]} || forging_enabled=0
+    [[ ${node_metrics} =~ cardano_node_metrics_cardano_build_info[[:space:]].*,version=\"([0-9.]*)\" ]] && running_node_version=${BASH_REMATCH[1]} || running_node_version="?"
+    [[ ${node_metrics} =~ cardano_node_metrics_cardano_build_info[[:space:]].*,revision=\"([0-9a-f]*)\" ]] && running_node_rev=${BASH_REMATCH[1]:0:8} || running_node_rev="?"
   fi
 }
 
@@ -764,11 +810,36 @@ slotInterval() {
   echo "(${SLOT_LENGTH} / ${ACTIVE_SLOTS_COEFF}) + 0.5" | bc -l | awk '{printf "%.0f\n", $1}'
 }
 
+# Description : Get current protocol params from either node or Koios
+# Error codes:
+# 1 : CLI - node socket not available
+# 2 : CLI - node response not valid json
+# 3 : Koios - general error
 getProtocolParams() {
-  PROT_PARAMS="$(${CCLI} ${NETWORK_ERA} query protocol-parameters ${NETWORK_IDENTIFIER} 2>/dev/null)"
-  read -ra PROT_PARAMS_VERSION <<<"$(jq -r '[ .protocolVersion.major //0, .protocolVersion.minor //0]| @tsv' <<<"${PROT_PARAMS}" 2>/dev/null)"
-  PROT_MAJOR=${PROT_PARAMS_VERSION[0]}
-  PROT_MINOR=${PROT_PARAMS_VERSION[1]}
+  if [[ -n ${KOIOS_API} ]]; then
+    [[ $(type -t println) = function ]] && println ACTION "curl -sSL -f -X GET -H \"accept: application/json\" ${KOIOS_API}/cli_protocol_params"
+    if ! PROT_PARAMS=$(curl -sSL -f -X GET -H "accept: application/json" "${KOIOS_API}/cli_protocol_params" 2>&1); then
+      return 3
+    fi
+  else
+    PROT_PARAMS="$(${CCLI} ${NETWORK_ERA} query protocol-parameters ${NETWORK_IDENTIFIER} 2>&1)"
+    if grep -q "Network.Socket.connect" <<< "${PROT_PARAMS}"; then
+      return 1
+    elif [[ -z "${PROT_PARAMS}" ]] || ! jq -er . <<< "${PROT_PARAMS}" &>/dev/null; then
+      return 2
+    fi
+  fi
+  # Set a collection of commonly used values
+  read -r PROT_MAJOR PROT_MINOR KEY_DEPOSIT POOL_DEPOSIT MIN_POOL_COST POOL_RETIRE_MAX_EPOCH DREP_DEPOSIT GOV_ACTION_DEPOSIT <<<"$(jq -r '[
+  .protocolVersion.major //0,
+  .protocolVersion.minor //0,
+  .stakeAddressDeposit //0,
+  .stakePoolDeposit //0,
+  .minPoolCost //0,
+  .poolRetireMaxEpoch //0,
+  .dRepDeposit //0,
+  .govActionDeposit //0
+  ] | @tsv' <<<"${PROT_PARAMS}" 2>/dev/null)"
   PROT_VERSION="${PROT_MAJOR}.${PROT_MINOR}"
   [[ ${PROT_MAJOR} -eq 0 ]] && return 1 || return 0
 }
@@ -792,6 +863,7 @@ set_default_vars() {
   [[ -z ${G_ACCOUNT} ]] && G_ACCOUNT="cardano-community"
 
   URL_RAW="https://raw.githubusercontent.com/${G_ACCOUNT}/guild-operators/${BRANCH}"
+  URL_DOCS="${URL_RAW}/docs/Scripts"
   export LC_ALL=C.UTF-8
   # special mapping of coreutils gdate to date for MacOS
   if [[ $(uname) == Darwin ]]; then
@@ -822,14 +894,41 @@ set_default_vars() {
   [[ -z ${WALLET_PAY_SK_FILENAME} ]] && WALLET_PAY_SK_FILENAME="payment.skey"
   [[ -z ${WALLET_HW_PAY_SK_FILENAME} ]] && WALLET_HW_PAY_SK_FILENAME="payment.hwsfile"
   [[ -z ${WALLET_PAY_ADDR_FILENAME} ]] && WALLET_PAY_ADDR_FILENAME="payment.addr"
+  [[ -z ${WALLET_PAY_SCRIPT_FILENAME} ]] && WALLET_PAY_SCRIPT_FILENAME="payment.script"
+  [[ -z ${WALLET_PAY_CRED_FILENAME} ]] && WALLET_PAY_CRED_FILENAME="payment.cred"
+  [[ -z ${WALLET_PAY_SCRIPT_CRED_FILENAME} ]] && WALLET_PAY_SCRIPT_CRED_FILENAME="payment.script.cred"
   [[ -z ${WALLET_BASE_ADDR_FILENAME} ]] && WALLET_BASE_ADDR_FILENAME="base.addr"
   [[ -z ${WALLET_STAKE_VK_FILENAME} ]] && WALLET_STAKE_VK_FILENAME="stake.vkey"
   [[ -z ${WALLET_STAKE_SK_FILENAME} ]] && WALLET_STAKE_SK_FILENAME="stake.skey"
   [[ -z ${WALLET_HW_STAKE_SK_FILENAME} ]] && WALLET_HW_STAKE_SK_FILENAME="stake.hwsfile"
   [[ -z ${WALLET_STAKE_ADDR_FILENAME} ]] && WALLET_STAKE_ADDR_FILENAME="reward.addr"
+  [[ -z ${WALLET_STAKE_SCRIPT_FILENAME} ]] && WALLET_STAKE_SCRIPT_FILENAME="stake.script"
+  [[ -z ${WALLET_STAKE_CRED_FILENAME} ]] && WALLET_STAKE_CRED_FILENAME="stake.cred"
+  [[ -z ${WALLET_STAKE_SCRIPT_CRED_FILENAME} ]] && WALLET_STAKE_SCRIPT_CRED_FILENAME="stake.script.cred"
   [[ -z ${WALLET_STAKE_CERT_FILENAME} ]] && WALLET_STAKE_CERT_FILENAME="stake.cert"
   [[ -z ${WALLET_STAKE_DEREG_FILENAME} ]] && WALLET_STAKE_DEREG_FILENAME="stake.dereg"
   [[ -z ${WALLET_DELEGCERT_FILENAME} ]] && WALLET_DELEGCERT_FILENAME="delegation.cert"
+  [[ -z ${WALLET_CATALYST_VK_FILENAME} ]] && WALLET_CATALYST_VK_FILENAME="catalyst.vkey"
+  [[ -z ${WALLET_CATALYST_SK_FILENAME} ]] && WALLET_CATALYST_SK_FILENAME="catalyst.skey"
+  [[ -z ${WALLET_CATALYST_QR_FILENAME} ]] && WALLET_CATALYST_QR_FILENAME="catalyst-qrcode.png"
+  [[ -z ${WALLET_GOV_DREP_VK_FILENAME} ]] && WALLET_GOV_DREP_VK_FILENAME="drep.vkey"
+  [[ -z ${WALLET_GOV_DREP_SK_FILENAME} ]] && WALLET_GOV_DREP_SK_FILENAME="drep.skey"
+  [[ -z ${WALLET_GOV_DREP_ID_FILENAME} ]] && WALLET_GOV_DREP_ID_FILENAME="drep.id"
+  [[ -z ${WALLET_GOV_DREP_SCRIPT_FILENAME} ]] && WALLET_GOV_DREP_SCRIPT_FILENAME="drep.script"
+  [[ -z ${WALLET_GOV_DREP_REGISTER_CERT_FILENAME} ]] && WALLET_GOV_DREP_REGISTER_CERT_FILENAME="drep-reg.cert"
+  [[ -z ${WALLET_GOV_DREP_RETIRE_CERT_FILENAME} ]] && WALLET_GOV_DREP_RETIRE_CERT_FILENAME="drep-ret.cert"
+  [[ -z ${WALLET_GOV_VOTE_DELEG_CERT_FILENAME} ]] && WALLET_GOV_VOTE_DELEG_CERT_FILENAME="vote-deleg.cert"
+  [[ -z ${WALLET_GOV_HW_DREP_SK_FILENAME} ]] && WALLET_GOV_HW_DREP_SK_FILENAME="drep.hwsfile"
+  [[ -z ${WALLET_GOV_CC_HOT_VK_FILENAME} ]] && WALLET_GOV_CC_HOT_VK_FILENAME="cc-hot.vkey"
+  [[ -z ${WALLET_GOV_CC_HOT_SK_FILENAME} ]] && WALLET_GOV_CC_HOT_SK_FILENAME="cc-hot.skey"
+  [[ -z ${WALLET_GOV_HW_CC_HOT_SK_FILENAME} ]] && WALLET_GOV_HW_CC_HOT_SK_FILENAME="cc-hot.hwsfile"
+  [[ -z ${WALLET_GOV_CC_HOT_ID_FILENAME} ]] && WALLET_GOV_CC_HOT_ID_FILENAME="cc-hot.id"
+  [[ -z ${WALLET_GOV_CC_COLD_VK_FILENAME} ]] && WALLET_GOV_CC_COLD_VK_FILENAME="cc-cold.vkey"
+  [[ -z ${WALLET_GOV_CC_COLD_SK_FILENAME} ]] && WALLET_GOV_CC_COLD_SK_FILENAME="cc-cold.skey"
+  [[ -z ${WALLET_GOV_HW_CC_COLD_SK_FILENAME} ]] && WALLET_GOV_HW_CC_COLD_SK_FILENAME="cc-cold.hwsfile"
+  [[ -z ${WALLET_GOV_CC_COLD_ID_FILENAME} ]] && WALLET_GOV_CC_COLD_ID_FILENAME="cc-cold.id"
+  [[ -z ${WALLET_DERIVATION_PATH_FILENAME} ]] && WALLET_DERIVATION_PATH_FILENAME="derivation.path"
+  [[ -z ${WALLET_MULTISIG_PREFIX} ]] && WALLET_MULTISIG_PREFIX="ms_"
   [[ -z ${POOL_ID_FILENAME} ]] && POOL_ID_FILENAME="pool.id"
   [[ -z ${POOL_HOTKEY_VK_FILENAME} ]] && POOL_HOTKEY_VK_FILENAME="hot.vkey"
   [[ -z ${POOL_HOTKEY_SK_FILENAME} ]] && POOL_HOTKEY_SK_FILENAME="hot.skey"
@@ -851,6 +950,7 @@ set_default_vars() {
   [[ -z ${ASSET_POLICY_ID_FILENAME} ]] && ASSET_POLICY_ID_FILENAME="policy.id"
   [[ -z ${CIP0094_POLL_URL} ]] && CIP0094_POLL_URL="https://raw.githubusercontent.com/cardano-foundation/CIP-0094-polls/main/networks/polls.json"
   [[ -z ${MITHRIL_DOWNLOAD} ]] && MITHRIL_DOWNLOAD="N"
+  [[ -z ${MITHRIL_SIGNER_ENABLED} ]] && MITHRIL_SIGNER_ENABLED="N"
   [[ -z ${STRICT_VERSION_CHECK} ]] && STRICT_VERSION_CHECK="Y"
   FG_BLACK='\e[30m'
   FG_RED='\e[31m'
@@ -929,8 +1029,9 @@ fi
 
 node_version="$(${CNODEBIN} version | head -1 | cut -d' ' -f2)"
 cli_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
-if ! versionCheck "8.7.3" "${node_version}" || ! versionCheck "8.17.0.0" "${cli_version}"; then
-  echo -e "\nKoios scripts have now been upgraded to support cardano-node 8.7.x ('${node_version}' found) / cardano-cli 8.17.x.x ('${cli_version}' found).\nPlease update cardano-node binaries (ensure to read release notes and update various configs using guild-deploy (use appropriate options to download/install/overwrite parts you need) or use tagged branches for older node version (eg: ./<script>.sh -b node-8.1.2 to switch scripts to an older branch).\n\n"
+
+if ! versionCheckNode "9.1.0" "${node_version}" || ! versionCheckNode "9.2.1.0" "${cli_version}"; then
+  echo -e "\nKoios scripts have now been upgraded to support cardano-node 9.1.x ('${node_version}' found) / cardano-cli 9.2.x.x ('${cli_version}' found).\nPlease update cardano-node binaries (ensure to read release notes and update various configs using guild-deploy (use appropriate options to download/install/overwrite parts you need) or use tagged branches for older node version (eg: ./<script>.sh -b node-8.9.4 to switch scripts to an older branch).\n\n"
   return 1
 fi
 
@@ -973,9 +1074,6 @@ if ! command -v "jq" &>/dev/null; then
   return 1
 fi
 
-NETWORK_ERA=$(${CCLI} latest query tip ${NETWORK_IDENTIFIER} 2>/dev/null | jq -r '.era //empty' | tr '[:upper:]' '[:lower:]')
-[[ -z ${NETWORK_ERA} ]] && NETWORK_ERA=latest
-
 read -ra CONFIG_CONTENTS <<<"$(jq -r '[ .AlonzoGenesisFile //"null", .ByronGenesisFile //"null", .ShelleyGenesisFile //"null", .Protocol //"Cardano", .TraceChainDb //"null", .EnableP2P //"false", .ConwayGenesisFile //"null"]| @tsv' "${CONFIG}" 2>/dev/null)"
 if [[ ${CONFIG_CONTENTS[4]} != "true" ]]; then
   echo "Could not find TraceChainDb when attempting to parse ${CONFIG} file in JSON format, please double-check the syntax of your config, or simply download it from guild-operators repository!"
@@ -991,11 +1089,11 @@ else
   [[ ! ${BYRON_GENESIS_JSON} =~ ^/ ]] && BYRON_GENESIS_JSON="$(dirname "${CONFIG}")/${BYRON_GENESIS_JSON}"
   [[ ! ${GENESIS_JSON} =~ ^/ ]] && GENESIS_JSON="$(dirname "${CONFIG}")/${GENESIS_JSON}"
   # if genesis files not found, exit with rc 1
-  [[ ! -f "${CONWAY_GENESIS_JSON}" ]] && echo "Byron genesis file not found: ${CONWAY_GENESIS_JSON}" && return 1
-  [[ ! -f "${ALONZO_GENESIS_JSON}" ]] && echo "Byron genesis file not found: ${ALONZO_GENESIS_JSON}" && return 1
+  [[ ! -f "${CONWAY_GENESIS_JSON}" ]] && echo "Conway genesis file not found: ${CONWAY_GENESIS_JSON}" && return 1
+  [[ ! -f "${ALONZO_GENESIS_JSON}" ]] && echo "Alonzo genesis file not found: ${ALONZO_GENESIS_JSON}" && return 1
   [[ ! -f "${BYRON_GENESIS_JSON}" ]] && echo "Byron genesis file not found: ${BYRON_GENESIS_JSON}" && return 1
   [[ ! -f "${GENESIS_JSON}" ]] && echo "Shelley genesis file not found: ${GENESIS_JSON}" && return 1
-  GENESIS_HASH="$(${CCLI} ${NETWORK_ERA} genesis hash --genesis "${GENESIS_JSON}")"
+  GENESIS_HASH="$(${CCLI} latest genesis hash --genesis "${GENESIS_JSON}")"
   PROTOCOL="${CONFIG_CONTENTS[3]}"
   P2P_ENABLED="${CONFIG_CONTENTS[5]}"
 fi
@@ -1100,6 +1198,9 @@ case ${NWMAGIC} in
     [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=0
 esac
 
+NETWORK_ERA=$(${CCLI} latest query tip ${NETWORK_IDENTIFIER} 2>/dev/null | jq -r '.era //empty' | tr '[:upper:]' '[:lower:]')
+[[ -z ${NETWORK_ERA} ]] && NETWORK_ERA=latest
+
 [[ ${OFFLINE_MODE} = "N" && ${SHELLEY_TRANS_EPOCH} -eq -1 ]] && getNodeMetrics && getShelleyTransitionEpoch
 
 # Return code 2 is used for scripts that want to source env but not fail due to a starting node
@@ -1111,7 +1212,7 @@ if [[ ${OFFLINE_MODE} = "N" && ! -S ${CARDANO_NODE_SOCKET_PATH} ]]; then
   return 2
 fi
 
-if [[ ${OFFLINE_MODE} = "N" ]] && ! getProtocolParams; then
+if [[ ${OFFLINE_MODE} = "N" && -z ${KOIOS_API} ]] && ! getProtocolParams; then
   echo -e "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}"
   return 2
 fi
